import Link from "next/link";

import { Button } from "@/components/ui/Button";
import { siteConfig } from "@/lib/site-config";

import { EmbeddedSignupSessionCapture } from "./EmbeddedSignupSessionCapture";
import styles from "./whatsapp-connect.module.scss";

type SearchParams = Promise<Record<string, string | string[] | undefined>>;

function getValue(
  source: Record<string, string | string[] | undefined>,
  key: string,
) {
  const value = source[key];

  return Array.isArray(value) ? value[0] : value;
}

export default async function WhatsAppConnectPage({
  searchParams,
}: {
  searchParams: SearchParams;
}) {
  const params = await searchParams;
  const state = getValue(params, "state")?.trim();

  return (
    <main className={styles.page}>
      {state ? <EmbeddedSignupSessionCapture state={state} /> : null}
      <p className={styles.eyebrow}>LAMARS onboarding</p>
      <h1 className={styles.title}>Connect your WhatsApp business account</h1>
      <p className={styles.lede}>
        Finish the connection through Meta and return to Lamars once the setup
        is done.
      </p>

      <section className={styles.card}>
        {state ? (
          <>
            <ul className={styles.list}>
              <li>
                <span className={styles.label}>What happens next:</span> Lamars
                will send you to Meta to authorize the WhatsApp connection.
              </li>
              <li>
                <span className={styles.label}>Secure context:</span> this page
                uses the signed connection state generated by Lamars.
              </li>
              <li>
                <span className={styles.label}>After approval:</span> we&apos;ll
                finish the connection with the Lamars backend and show the final
                result here.
              </li>
            </ul>

            <div className={styles.actions}>
              <Button href={`/connect/whatsapp/meta/start?state=${encodeURIComponent(state)}`}>
                Continue with Meta
              </Button>
              <p className={styles.hint}>
                If you opened this from the Lamars app, come back to the app
                after the connection is complete.
              </p>
            </div>
          </>
        ) : (
          <>
            <p className={styles.hint}>
              This connection link is missing a valid state. Please go back to
              the Lamars app and start the WhatsApp connection again.
            </p>
            <div className={styles.actions}>
              <Button href={siteConfig.url} variant="secondary">
                Back to lamars.ai
              </Button>
            </div>
          </>
        )}
      </section>

      <Link className={styles.backLink} href="/">
        Back to home
      </Link>
    </main>
  );
}
